services:
  app:
    container_name: Merchant-frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_BAKE=true
      - NODE_OPTIONS=--max-old-space-size=4096


