name: marchent pipeline
on:
  push:
    branches: [ test ] # add test branch for testing pipeline 
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Connect and deploy to EC2
        run: |
          REPO_DIR=/home/${{ vars.SERVICE_NAME }}
          BRANCH="${GITHUB_REF##*/}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "export BRANCH='$BRANCH'; export REPO_DIR='$REPO_DIR'; bash -s" << EOF
            echo "Connection successful"
            if [ -d "$REPO_DIR" ]; then
              cd "$REPO_DIR"
              sudo git config --global --add safe.directory "$REPO_DIR"
              sudo git fetch origin "$BRANCH"
              sudo git reset --hard origin/"$BRANCH"
              sudo git clean -fd
            else
              echo "start cloning repo"
              sudo git clone https://${{ secrets.TOKEN_GIT }}@github.com/${{ github.repository }} "$REPO_DIR"
              cd "$REPO_DIR"
              sudo git fetch origin "$BRANCH"
              sudo git checkout "$BRANCH"
            fi
          EOF

      - name: Trigger user repo pipeline
        env:
          PAT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          # Ensure PAT_TOKEN is a valid GitHub PAT with repo:workflow and repo permissions
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $PAT_TOKEN" \
            https://api.github.com/repos/Board-Pins/User_Management/dispatches \
            -d '{"event_type":"trigger-ci-from-merchant"}')
          echo "HTTP Status: $response"
          if [ "$response" -eq 204 ]; then
            echo "Successfully sent repository_dispatch to user_managment ci/cd"
          else
            echo "Failed to send repository_dispatch. Status: $response"
            exit 1
          fi
